language: c
sudo: required
dist: trusty
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
    global:
        - PACKAGE="mirage-xen"
    matrix:
        - OCAML_VERSION=4.08
        - OCAML_VERSION=4.07
        - OCAML_VERSION=4.06
